main: com.projectbarks.nxannouncer.NXAnnouncer
name: NXAnnouncer
version: 0.2
author: ProjectBarks
description: Simple Announcer Plugin.

commands:
   nxannouncer:
      description: Modify and view the NXAnnouncer
      aliases: [announcer]
      usage: /<command> [function]
      permission: nxannouncer.admin
      permission-message: You don't have <permission>
